version: "3"

services:
  #######################
  #setup node container
  #######################

  server:
    container_name: canvis-server
    build: ./server
    #expose: - 4000
    #enviroment:
    #API_HOST: http://localhost
    #APP_SERVER_PORT: 4000
    ports:
      - "8080:8080"
    volumes:
      - ./server/src:/srv/app/admin-server/src
    command: npm run start

  ########################
  #setup client container
  ########################

  client:
    build: ./client
    container_name: canvis-react
    #enviroment:
    #  - REACT_APP_PORT=3000
    #expose:
    #  - 3000
    ports:
      - "8081:8081"
    volumes:
      - ./client/src:/srv/app/client-admin/src
      - ./client/public:/srv/app/client-admin/public
    links:
      - server
    command: npm run start
